### PR TITLE
updated styles for selectors; added blue style for selects

### PR DESCRIPTION
**Pull request by davidsingal**
Added purple styles for selects

### CODE REVIEW

**Comment by andresgnlez** [comment]
@davidsingal where is the purple? 🤔

**Review by andresgnlez — APPROVED** [review]
@davidsingal where is the purple? 🤔

**Comment by davidsingal** [comment]
It's in the analysis page, in the sidebar where you can select a scenario to compare.

**Comment by andresgnlez** [comment]
image
 This? Anyway, I found a mismatch of styles here.

**Pull request merged**
