### PR TITLE
Empty expanded tree parent

### PR DESCRIPTION
**Pull request by JoaquinTrinanes**
### General description

Refactor or tree selectors to solve some UI issues and improve usability.

https://vizzuality.atlassian.net/browse/LANDGRIF-1068
https://vizzuality.atlassian.net/browse/LANDGRIF-1030
https://vizzuality.atlassian.net/browse/LANDGRIF-1026

### CODE REVIEW

**Comment by andresgnlez** [comment]
image

For some reason, when the user clicks on the filters and the dropdown displays on the analysis page, the **suppliers** selector has the focus by default. Not a big deal, but it's weird. This issue also happens in staging, which is unrelated to the latest code changes.

image


Last thing; when a user clicks on the right zone of the selector (around the chevron), the selector opens up but the focus is not set in the selector (despite having the focus-based styles applied) preventing the user to type in the box.

**Review by andresgnlez — CHANGES_REQUESTED** [review]
image

For some reason, when the user clicks on the filters and the dropdown displays on the analysis page, the **suppliers** selector has the focus by default. Not a big deal, but it's weird. This issue also happens in staging, which is unrelated to the latest code changes.

image


Last thing; when a user clicks on the right zone of the selector (around the chevron), the selector opens up but the focus is not set in the selector (despite having the focus-based styles applied) preventing the user to type in the box.

**Review by davidsingal — CHANGES_REQUESTED** [review]
Changelog is not updated

**Review by alexeh — COMMENTED** [review]
I've seen some stuff that I am not sure it is right to left as is:

First of all, we should make sure that all the team is OK with the design of the 'search dropdown', since the font, its size.. changes:
image

Second, I realise that if you select a 'only son' through the dropdown, the parent gets shown in the field, however if you select it via search, the son gets shown:
image

image

Lastly, I know that the search match is flexible, but I am not sure if some results have any sense at all, check below:
image

image

I checked other behaviours and seems to work fine, but please @davidsingal @andresgnlez  
have a look at this.

I haven't checked for regressions, I will do a bit later

**Comment by alexeh** [comment]
Also, @JoaquinTrinanes I realised this branch was originally taken from dev, but now points to staging. This can be potentially evil, there are some commits that are not part of this hotfix, so please be aware of that. Also, if its possible to squash them that would be great, so we can have a cleaner rebasing for everyone

**Pull request merged**
