### PR TITLE
pass h3 version to entrypoint

### PR DESCRIPTION
**Pull request by alexeh**
### General description

Pass H3 version to entrypoint.sh running a probably redundant pgxn command. Please check if both are actually required

### Designs

_Link to the related design prototypes (if applicable)_

### Testing instructions

Run locally the image. With this code this CI run should also pass. Check after merging that CI is running ok

- Apart from the added feature / bug fix, check overall performance, styling...

## Checklist before merging

- [ ] Branch name / PR includes the related Jira ticket Id.
- [ ] Tests to check core implementation / bug fix added.
- [ ] All checks in Continuous Integration workflow pass.
- [ ] Feature functionally tested by reviewer(s).
- [ ] Code reviewed by reviewer(s).
- [ ] Documentation updated (README, CHANGELOG...) (if required)

### CODE REVIEW

**Review by BielStela — COMMENTED** [review]
maybe also add the `--yes` options so that in case it breaks again we only see the pgxn error message and not the full python exception trace?

**Review by BielStela — APPROVED** [review]
:1st_place_medal:

**Comment by alexeh** [comment]
> maybe also add the `--yes` options so that in case it breaks again we only see the pgxn error message and not the full python exception trace?

I agree, I forgot the pgxn yes issue in the middle of the chaos. 

Added in [fe444e5](https://github.com/Vizzuality/landgriffon/pull/636/commits/fe444e5da2b20489da44a0978bfed9641e0d8002)

**Comment by tiagojsag** [comment]
use https://github.com/Vizzuality/landgriffon/pull/637 instead

**Pull request closed without merging**
